# Generated by Django 3.0.2 on 2020-01-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotcomponent',
            old_name='protocolId',
            new_name='protocol',
        ),
    ]
