# Generated by Django 3.0.2 on 2020-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200121_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotcomponent',
            name='topic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
