# Generated by Django 3.0.2 on 2020-02-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_iotcomponent_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deleted_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XSensorIOTComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('iot_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.IOTComponent')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Sensor')),
            ],
        ),
    ]
