# Generated by Django 3.0.2 on 2020-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProtocolUtils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocollog',
            name='topic',
            field=models.TextField(default=''),
        ),
    ]
